spring:
  datasource:
    url: jdbc:h2:mem:codeforge_dev;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
      path: /h2-console
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

app:
  h2:
    tcp:
      enabled: true

server:
  port: ${PORT:5000}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Minimal Actuator exposure for health/info
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
