spring:
  datasource:
    url: jdbc:h2:mem:codeforge_dev;DB_CLOSE_DELAY=-1
    username: sa
    password:
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
app:
  h2:
    tcp:
      enabled: true